# Generated by Django 4.2.4 on 2023-11-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
