# Generated by Django 4.2.4 on 2023-11-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0010_alter_forecasttemplate_last_scraped'),
        ('website', '0005_remove_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='datascraper.location'),
        ),
    ]
