# Generated by Django 4.2.4 on 2023-11-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_bio_profile_about_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
