# Generated by Django 4.2 on 2023-08-06 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='scraped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 16, 1, 34, 258177)),
        ),
    ]
