# Generated by Django 4.2 on 2023-08-14 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0002_alter_archive_scraped_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='scraped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 17, 12, 52, 154620)),
        ),
    ]
