# Generated by Django 4.2.4 on 2023-10-04 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0008_remove_forecast_prediction_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasttemplate',
            name='last_scraped',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 20, 7, 50, 374749)),
        ),
    ]
