# Generated by Django 4.2.4 on 2023-11-15 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0011_location_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimezoneChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('last_scraped', models.DateTimeField(default=datetime.datetime(2023, 11, 15, 15, 12, 30, 749019))),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(choices=[('q', 'w')], default='MRS', max_length=40),
        ),
    ]
