# Generated by Django 4.2.4 on 2023-11-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0012_timezonechoice_alter_location_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezonechoice',
            name='last_scraped',
        ),
        migrations.RemoveField(
            model_name='timezonechoice',
            name='value',
        ),
        migrations.AddField(
            model_name='timezonechoice',
            name='json_data',
            field=models.JSONField(default={}),
        ),
    ]
