# Generated by Django 4.2.4 on 2023-11-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0014_alter_timezonechoice_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(choices=[['q', 'Q'], ['a', 'A']], default='MRS', max_length=40),
        ),
        migrations.AlterField(
            model_name='timezonechoice',
            name='json_data',
            field=models.JSONField(default={}),
        ),
    ]
