# Generated by Django 4.2.4 on 2023-11-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0015_alter_location_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezonechoice',
            name='json_data',
            field=models.JSONField(),
        ),
    ]
