# Generated by Django 4.2.4 on 2023-11-20 19:12

import datascraper.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datascraper', '0018_location_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasttemplate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only roman characters are allowed.'), datascraper.models.validate_first_upper]),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only roman characters are allowed.'), datascraper.models.validate_first_upper]),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only roman characters are allowed.'), datascraper.models.validate_first_upper]),
        ),
    ]
