# Generated by Django 4.2.4 on 2023-11-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0020_rename_location_relative_url_forecasttemplate_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivetemplate',
            old_name='location_relative_url',
            new_name='url',
        ),
    ]
