# Generated by Django 4.2.4 on 2023-11-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0022_archivetemplate_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivetemplate',
            unique_together={('archive_source', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='forecasttemplate',
            unique_together={('forecast_source', 'location')},
        ),
    ]
