# Generated by Django 4.2.4 on 2023-11-24 14:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0023_alter_archivetemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasttemplate',
            name='last_scraped',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 3, 0)),
        ),
        migrations.AlterField(
            model_name='forecasttemplate',
            name='url',
            field=models.CharField(max_length=100, validators=[django.core.validators.URLValidator(message='It is not url.')]),
        ),
    ]
