# Generated by Django 4.2.4 on 2023-11-24 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0024_alter_forecasttemplate_last_scraped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivesource',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='archivetemplate',
            name='url',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.URLValidator(message='It is not url.')]),
        ),
        migrations.AlterField(
            model_name='forecasttemplate',
            name='url',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.URLValidator(message='It is not url.')]),
        ),
    ]
