# Generated by Django 4.2.4 on 2023-11-25 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0025_alter_archivesource_url_alter_archivetemplate_url_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='archive',
            new_name='datascraper_archive_1acdc0_idx',
            old_fields=('archive_template', 'record_datetime'),
        ),
        migrations.AlterField(
            model_name='archivetemplate',
            name='url',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.URLValidator(message='It is not Url.')]),
        ),
        migrations.AlterField(
            model_name='forecasttemplate',
            name='url',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.URLValidator(message='It is not Url.')]),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['scraped_datetime', 'forecast_template'], name='datascraper_scraped_124b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['forecast_template', 'prediction_range_hours', 'forecast_datetime'], name='datascraper_forecas_b62599_idx'),
        ),
    ]
