# Generated by Django 4.2.4 on 2023-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0026_rename_archive_archive_template_record_datetime_datascraper_archive_1acdc0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
