# Generated by Django 4.2.4 on 2023-12-02 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0028_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasttemplate',
            name='url',
            field=models.CharField(max_length=500, unique=True, validators=[django.core.validators.URLValidator(message='It is not Url.')]),
        ),
    ]
