# Generated by Django 4.2.4 on 2023-12-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0030_alter_archivetemplate_url_alter_forecasttemplate_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivesource',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='archivetemplate',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='forecastsource',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='forecasttemplate',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
