# Generated by Django 4.2.4 on 2023-12-27 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datascraper', '0031_alter_archivesource_url_alter_archivetemplate_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivesource',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
