# Generated by Django 4.2.4 on 2023-12-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0032_archivesource_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivesource',
            old_name='id',
            new_name='scraper_class',
        ),
        migrations.RenameField(
            model_name='forecastsource',
            old_name='id',
            new_name='scraper_class',
        ),
    ]
