# Generated by Django 4.2.4 on 2024-01-15 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0033_rename_id_archivesource_scraper_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasttemplate',
            name='last_scraped',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
