# Generated by Django 4.2.4 on 2023-11-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datascraper', '0010_alter_forecasttemplate_last_scraped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='profile_avatars')),
                ('favorite_location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='datascraper.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
