# Generated by Django 4.2.4 on 2023-11-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_personal_data',
            field=models.BooleanField(default=True),
        ),
    ]
